// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "10b796ec-3f65-451b-a81f-0da050e1972e";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedColorChange();
void onLedStatusChange();

String led_color;
float lux_level;
float temperature;
bool led_status;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led_color, READWRITE, ON_CHANGE, onLedColorChange);
  ArduinoCloud.addProperty(lux_level, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 0 * SECONDS, NULL);
  ArduinoCloud.addProperty(led_status, READWRITE, ON_CHANGE, onLedStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
